// ***************************************************************************************
// * Supreme Commander Random Map Generator
// * Copyright 2014  Jonathan Brewer
// * Filename: SaveFile.cs
// ***************************************************************************************
// * 
// * This program is free software; you can redistribute it and/or modify
// * it under the terms of the GNU General Public License as published by
// * the Free Software Foundation; either version 3 of the License, or
// * (at your option) any later version.
// * 
// * This program is distributed in the hope that it will be useful,
// * but WITHOUT ANY WARRANTY; without even the implied warranty of
// * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// * GNU General Public License for more details.
// *
// * You should have received a copy of the GNU General Public License
// * along with this program; if not, write to the Free Software Foundation,
// * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
// ***************************************************************************************


using System.Collections.Generic;

public class SaveFile
{
    private ScenarioFile _scenario;
    private List<Marker> _markers;
    public int AreaCount;
    public int UnitCount;
    public int GroupCount;
    public int PlatoonCount;

    public int QueueCount;
    public SaveFile(ScenarioFile Scenario, List<Marker> MarkerList)
    {
        _scenario = Scenario;
        _markers = MarkerList;

    }
    public void SaveScriptFile()
    {
        System.IO.StreamWriter sf = new System.IO.StreamWriter(_scenario.MapSavePath, false);

        sf.WriteLine("--[[                                                                           ]]--");
        sf.WriteLine("--[[  Automatically generated code (do not edit)                               ]]--");
        sf.WriteLine("--[[   Code generated by Duck_42's Map Generator                               ]]--");
        sf.WriteLine("--[[                                                                           ]]--");
        sf.WriteLine("--[[  Scenario                                                                 ]]--");
        sf.WriteLine("--[[                                                                           ]]--");
        sf.WriteLine("Scenario = {");
        sf.WriteLine("    next_area_id = '" + AreaCount + 1 + "',");
        sf.WriteLine("    next_queue_id = '" + QueueCount + 1 + "',");
        sf.WriteLine("    next_platoon_id = '" + PlatoonCount + 1 + "',");
        sf.WriteLine("    next_army_id = '" + _scenario.ArmyCount + 5 + "',");
        sf.WriteLine("    next_group_id = '" + GroupCount + 1 + "',");
        sf.WriteLine("    next_unit_id = '" + UnitCount + 1 + "',");
        sf.WriteLine("    Props = {},");
        sf.WriteLine("    Areas = {},");
        sf.WriteLine("    Chains = {},");
        sf.WriteLine("    Orders = {},");
        sf.WriteLine("    Platoons = {},");
        sf.WriteLine(Save_Army.GetArmiesText(_scenario.ArmyCount));
        sf.WriteLine("    MasterChain = {");
        sf.WriteLine("        ['_MASTERCHAIN_'] = {");
        sf.WriteLine("            Markers = {");

        foreach (Marker sm in _markers)
        {
            sf.WriteLine(sm.ToString());
        }

        sf.WriteLine("            },");
        sf.WriteLine("        },");
        sf.WriteLine("    },");
        sf.WriteLine("}");

        sf.WriteLine("");
        sf.Close();
    }
}